### ISSUE TITLE
Twig_Function usage in SettingExtension

### ISSUE THREAD

**Issue by HermanBilous** [phpmob/settings-bundle#1]
Hi, thanks for this bundle!

I have an issue with `SettingExtension`. It's instantiating object of `\Twig_Function` in `getFunctions` method. But this class became deprecated in twig 1.12, and abstract in 2.0. Since I'm using twig 2.0 I receive an error.

I resolved this issue by creating my own SettingExtension and replaced the original one with it using compiler pass.

First of all I think that twig should be added to the dependencies.
And also it would be nice to use \Twig_SimpleFunction, so people wouldn't have to use twig 1.0.

**Comment by liverbool** [comment]
👍  Thanks to your reporting, now already fixed via https://github.com/phpmob/settings-bundle/releases/tag/1.0.1

**Comment by HermanBilous** [comment]
That was fast!

Thanks!
